# Generated by Django 2.1 on 2018-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObjInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.BooleanField(default=True)),
                ('height', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('qq_howl', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('passwrod', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(default='未命名', max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=True)),
                ('height', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('qq_howl', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('single', models.BooleanField(default=False)),
                ('value1', models.CharField(max_length=30)),
                ('value2', models.CharField(max_length=30)),
                ('value3', models.CharField(max_length=30)),
            ],
        ),
    ]
