# Generated by Django 2.1 on 2018-08-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('h2_home', '0002_userinfo_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labelinfo',
            options={'verbose_name_plural': '个性标签'},
        ),
        migrations.AlterModelOptions(
            name='objinfo',
            options={'verbose_name_plural': '对象'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '同学'},
        ),
    ]
